os: linux
dist: xenial

language: node_js

node_js:
- '11.9'

script:
  - wget -N https://github.com/lucidworks/banana/archive/v1.6.26.zip
  - unzip -q v1.6.26.zip -d ./stats 
  - mkdir -p /tmp/banana
  - cp -fr ./stats/banana-1.6.26/src/. /tmp/banana
  - cp -f ./banana-files/config.js /tmp/banana/config.js
  - cp -f ./banana-files/settings.js /tmp/banana/app/components/settings.js
  - rm -fr /tmp/banana/app/dashboards/
  - mkdir -p /tmp/banana/app/dashboards
  - cp -r ./dashboards /tmp/banana/app/
  - rm -rf ./stats/banana-1.6.26/src
  - rm v1.6.26.zip

deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY_ID}
    bucket: static.kbharkiv.dk
    cache_control: 'no-cache'
    local_dir: /tmp/banana
    upload_dir: ${DEPLOY_DIR}
    acl: public_read
    region: eu-west-1
    overwrite: true
    cleanup: false
    on:
      all_branches: true